### PR TITLE
Add support for Gatsby v5

### LINKED ISSUE #93: Gatsby v5 campatibility
**Describe the bug**
I've updated to Gatsby v5 and now I'm getting "Plugin gatsby-plugin-gdpr-cookies is not compatible with your gatsby version 5.0.1 - It requires gatsby@^2.24.77 || ^3.0.0 || ^4.0.0" This plugin isn't compatible?

 "gatsby-plugin-gdpr-cookies": "^2.0.9",
 "react": "^18.2.0",
 "gatsby": "^5.0.1",

### PR DESCRIPTION
**Pull request by spencerwhyte**
Fixes #93

### CODE REVIEW

**Comment by garrettboatman** [comment]
@andrezimpel - the plugin appears to work great with Gatsby v5. I have it running on Gatsby Cloud with `NPM_CONFIG_LEGACY_PEER_DEPS=true`.

Can we get this merged?

**Comment by Minomichu** [comment]
Was there any chance this could be merged? 🥺🙏

**Comment by andrezimpel** [comment]
Ahhh. Sorry I was so busy (and sick). It's merged now.

**Comment by Minomichu** [comment]
Thank you soo much ⭐️ 🙂

**Pull request merged**
